<?php

function lang($char){
    static $lang = array(
    // global chars
    'EDIT'     => 'edit',
    'UPDATE'   => '&#xf021; update',
    'SAVE'     => 'save',
    'DELETE'   => 'delete',
    'ADD'      => 'add',
    'ACTIVATE' => 'activate',
    'APPROVE'  => 'approve',
    'INSERT'   => '&#xf1d8; insert',
    'TAGS'     => 'tags',
    'TAGS_EX'  => 'enter tags siparite by coma (ex: tag1,tag2,...)',
    'VIEWS'    => 'views',
    // navbar chars
    'X_SHOP'          => 'shop-GO',
    'NOT_ACIVATE_YET' => 'your account not activate yet , please wait the admin approve your account to show all options',
    'NEW_ITEM'        => 'new item',
    'MY_PROFILE'      => 'my profile',
    'MY_ITEMS'        => 'my items',
    'MY_COMMENTS'     => 'my comments',
    'LOGOUT'          => 'logout',
    'LOGIN_SIGNUP'    => 'login/signUp',
    'CATEGORIES'      => 'categories',
    // sharing chars
    'RESET'            => '&#xf2f1; reset',
    'NOT_APPR'        => 'not approved',
    'IMG_SIZE_>2MB'   => 'image size is larger than <b>2MB</b>',
    'IMG_NOT_ALLOWED' => 'the image type is not allowed<br/> The extensions allowed is : ',
    'IMG_EMPTY'       => 'image cant be <b>empty</b>',
    'DELETED'         => 'is deleted',
    'ALREADY_EXIST'   => 'already exist',
    // pages : items, newAds, showAds, index
    'ADD_NEW_ADS'      => 'add new item',
    'ADS_NAME'         => 'item name',
    'ADS_DESCR'        => 'item description',
    'ADS_PRICE'        => 'item price ($)',
    'ADS_STATUS'       => 'item status',
    'ADS_MADE'         => 'country made',
    'ITEM_IMG'         => 'item image',
    'CAT'              => 'category',
    'ADD_ADS'          => '&#xf217; add item',
    'DELETE_ADS'       => 'delete item',
    'EDIT_ADS'         => '&#xf044; edit ads',
    'UPDATE_ADS'       => 'update ads',
    'ADS_NAME_HOLDER'  => 'item name',
    'ADS_DESCR_HOLDER' => 'item description length larger than 10 chars',
    'ADS_PRICE_HOLDER' => 'item price ($) in numbers',
    'ADS_MADE_HOLDER'  => 'country made length larger than 2 chars',
    'ALL_ITEMS'       => 'all items',
    'DESCR'           => 'description',
    'ADD_BY'          => 'added by',
    'ADD_DATE'        => 'adding date',
    'PRICE'           => 'price',
    'ADD_CMNT'        => 'add comment',
    'PLEASE_LOG'      => 'please login or sign-up to add comment',
    'ITEM_NAME_EMPTY' => 'item name cant be <b>empty</b>',
    'ITEM_DESC_EMPTY' => 'item description cant be <b>empty</b>',
    'ITEM_PRICE_EMPTY'=> 'item price cant be <b>empty</b>',
    'ITEM_NAME_<_2'   => 'item name must be greater than <b>2 chars</b>',
    'ITEM_DESC_<_10'  => 'item description must be greater than <b>10 chars</b>',
    'ITEM_MADE_<_3'   => 'item made must be greater than <b>3 chars</b>',
    'ITEM_PRICE_<_1'  => 'item price must be greater than <b>1 chars</b>',
    'ITEM_PRICE_NUM'  => 'item price must be number',
    'ITEM_ADDED'      => 'your advertise is added , please wait the admin approved',
    'NO_ITEM'         => 'There is no items to show',
    'NO_CMNTS'        => 'There is no comments to show',
    'ITEM_UPDATED'    => 'your advertise is updated',
    'NO_ID_ITEM_WAIT' => 'There is no such id or the item wainting the approve by admin',
    // pages: login, profile
    'USERNAME'        => 'username',
    'FULLNAME'        => 'full name',
    'EMAIL'           => 'e-mail',
    'PASSWORD'        => 'password',
    'DATE_REG'        => 'date register',
    'LOGIN'           => 'login',
    'SIGN_UP'         => 'sign-up',
    'USERNAME_HOLDER' => 'type username',
    'LOGIN_BTN'       => '&#xf2a7; login',
    'FULLNAME_HOLDER' => 'type your fullname',
    'CMNT_HOLDER'     => 'type your comment',
    'NEW_PASS'        => 'new password',
    'CON_PASS'        => 'confirm password',
    'SIGN_UP_BTN'     => '&#xf090; sign up',
    'EDIT_PROFILE'    => 'edit profile',
    'LEAVEBLANC'      => 'leave me blanc if you dont want to change',
    'EMAIL_HOLDER'    => 'type a valide email',
    'ACC_UPDATE'      => 'your account is updated',
    'ALL_ITEMS_ME'    => 'all my items',
    'MY_INFO'         => 'my information',
    'SHOW_ALL'        => 'show all my items',
    'LATEST_4_ADS'    => 'my latest 4 items',
    'ALL_MY_CMNTS'    => 'all my comments',
    'USERNAME_EMPTY'  => 'username cant be <b>empty</b>',
    'FULLNAME_EMPTY'  => 'fullname cant be <b>empty</b>',
    'PASS_EMPTY'      => 'password cant be <b>empty</b>',
    'EMAIL_EMPTY'     => 'email cant be <b>empty</b>',
    'USERNAME_<_4'    => 'username must be greater than <b>4 chars</b>',
    'FULLNAME_<_6'    => 'fullname must be greater than <b>6 chars</b>',
    'PASS_NO_MUTCH'   => 'password not mutch',
    'REG_OK'          => 'congrate you are now registred'
  );

  return $lang[$char];
}